services:
  redis:
    image: redis
    env_file:
      - ./in-memory-cache/config.env
    networks:
      default:
        ipv4_address: 192.168.1.3

  server:
    image: nawaphon2539/golang:gin-play
    ports:
      - "1002:8080"
    env_file:
      - ./service/config.env
    networks:
      default:
        ipv4_address: 192.168.1.2
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started

  db:
    image: postgres
    env_file:
      - ./db/config.env
    networks:
      default:
        ipv4_address: 192.168.1.4
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      retries: 3
      start_period: 0s
      timeout: 30s

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.1.0/28
          gateway: 192.168.1.1