services:
  redis:
    image: redis
    env_file:
      - ./in-memory-cache/config.env
    networks:
      default:
        ipv4_address: 192.168.1.3

  server:
    image: nawaphon2539/golang:gin-play
    ports:
      - "1002:8080"
    env_file:
      - ./service/config.env
    networks:
      default:
        ipv4_address: 192.168.1.2

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.1.0/29
          gateway: 192.168.1.1