info:
  contact: {}
paths:
  /cache/hello-world/{key}:
    get:
      consumes:
      - application/json
      description: Get value from cache by key
      parameters:
      - description: Key
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: value":"string
          schema:
            additionalProperties: true
            type: object
      tags:
      - CacheTestHandler
  /cache/set/{key}/{value}:
    post:
      consumes:
      - application/json
      description: Set value in cache with key
      parameters:
      - description: Key
        in: path
        name: key
        required: true
        type: string
      - description: Value
        in: path
        name: value
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: message":"Cache set successfully
          schema:
            additionalProperties: true
            type: object
      tags:
      - CacheTestHandler
  /hello-world:
    get:
      consumes:
      - application/json
      description: Get Hello World Message
      operationId: main-handlers
      produces:
      - application/json
      responses:
        "200":
          description: 'message":"Hello World", "date" : "time.Time'
          schema:
            additionalProperties: true
            type: object
swagger: "2.0"
